name: App 1 Build and deploy CI

# on: workflow_dispatch
on:
  push:
    branches: [main, develop]
    paths: [app1/**]

jobs:

  common:
    runs-on: ubuntu-latest
    outputs:
      branch: ${{ steps.extract_branch.outputs.branch }}

    steps:
      - name: Do Common steps
        run: echo "Do Common steps..."
      
      - name: Extract branch name
        id: extract_branch
        shell: bash
        run: echo "::set-output name=branch::$(echo ${GITHUB_REF#refs/heads/})"

      - name: DIsplay Common Context object
        run: echo '${{ toJSON(github) }}'

  deploy-staging:
    needs: common
    runs-on: ubuntu-latest
    environment: staging
    if: ${{ needs.common.outputs.branch == 'develop' }}

    steps:
      - name: Do Staging steps
        run: echo "Do Staging steps...."

      - uses: actions/checkout@v3

      - name: Deploy to Azure Storage Account (Staging)
        uses: rnakamine/azure-files-upload@v1.0.0
        with:
          connection_string: ${{ secrets.AZURE_STORAGE_CONNECTION_STRING }}
          source: ./app1
          destination: app1

      - name: DIsplay Staging Context object
        run: echo '${{ toJSON(github) }}'

  deploy-production:
    needs: common
    runs-on: ubuntu-latest
    environment: production
    if: ${{ needs.common.outputs.branch == 'main' }}

    steps:
      - name: Do Production steps
        run: echo "Do Production steps..."

      - uses: actions/checkout@v3

      - name: Deploy to Azure Storage Account (Production)
        uses: rnakamine/azure-files-upload@v1.0.0
        with:
          connection_string: ${{ secrets.AZURE_STORAGE_CONNECTION_STRING }}
          source: ./app1
          destination: app1

      - name: DIsplay Production Context object
        run: echo '${{ toJSON(github) }}'

